### ISSUE TITLE
Incompatible with Kibana 6.3.0

### ISSUE THREAD

**Issue by fenneh** [gbrian/grafana-timelion-datasource#12]
Plugin appears to not work with Kibana 6.3.0 (from what I can tell). I've replaced all references to esVersion and kbnversion. It previously worked with 6.0.0.

Queries come back without errors, just appears to be no data.

**Comment by Sathishruw** [comment]
where to replace the esVersion?

**Comment by Sathishruw** [comment]
+1

**Comment by gbrian** [comment]
@fenneh ,

Tested with the demo and you should set "6.3.1" as the value of header: `kbn-version`
BTW I'll move those values as plugin settings. Thanks

![image](https://user-images.githubusercontent.com/767180/43369224-8b2aecfc-936a-11e8-8f36-7b3389c295f9.png)

**Comment by fenneh** [comment]
I'll triple check what's being passed around but it didn't seem to be working.

**Comment by gbrian** [comment]
Currently working on https://github.com/gbrian/grafana-timelion-datasource/pull/13
I'll tell when done!

**Comment by gbrian** [comment]
@fenneh Tested and working with latest Kibana 6.3.1
Please update to the latest version as I had to change the way the time was sent to Timelion.

![image](https://user-images.githubusercontent.com/767180/43441596-a8c4d840-949b-11e8-8a3e-0154a5738627.png)
