### ISSUE TITLE
How to run plugin?

### ISSUE THREAD

**Issue by Yakud** [gbrian/grafana-timelion-datasource#2]
Hi! I tried to run plugin with grafana. It first view i think all ok, but if a select Timelion in data source section i have an error: 
`boot.07485e0c.js:6 GET http://grafana.xhamster.com:3001/public/traceur?bust=1503042242033 404 (Not Found)`
`Plugin component error Error: (SystemJS) XHR error (404 Not Found) loading http://grafana.xhamster.com:3001/public/traceur?bust=1503042242033
	Error: XHR error (404 Not Found) loading http://grafana.xhamster.com:3001/public/traceur?bust=1503042242033
	Error loading http://grafana.xhamster.com:3001/public/traceur
	Unable to load transpiler to transpile http://grafana.xhamster.com:3001/public/plugins/grafana-timelion-datasource/module.js
	Error loading http://grafana.xhamster.com:3001/public/plugins/grafana-timelion-datasource/module.js`

<img width="647" alt="2017-08-18 10 47 22" src="https://user-images.githubusercontent.com/796742/29449372-1b30fe7c-8403-11e7-8654-2a04a0fc2757.png">
<img width="368" alt="2017-08-18 10 47 30" src="https://user-images.githubusercontent.com/796742/29449375-1d596806-8403-11e7-8ae6-33225afe2d0d.png">

What am I doing wrong?

**Comment by gbrian** [comment]
@Yakud ,
Ops sorry, did not see this case. Did it work? If so, what was the problem?

**Comment by Yakud** [comment]
@gbrian Yes, all work perfect! Thank u for the plugin! It's really help to me for a move from kibana
