### ISSUE TITLE
HTTP Error Internal Server Error

### ISSUE THREAD

**Issue by trumpet7347** [gbrian/grafana-timelion-datasource#4]
I am reciving an Internal Server Error when I try to setup the Timelion data source.

![image](https://user-images.githubusercontent.com/4286108/31743226-f923b48a-b41f-11e7-9290-28881c0e267f.png)

Is this normal, you are not really to clear in the read me what server I should actually be setting the url to, is it suppose to be an elasticsearch node, or the kibana instance.

**Comment by gbrian** [comment]
@trumpet7347 ,
Sorry you are right, must be the Kibana server. READ.ME updated!
